name: Setup BEAM
inputs:
  otp-version:
    description: "The OTP version"
    required: true
  elixir-version:
    description: "The Elixir version (optional)"
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/../install.sh ${{ inputs.otp-version }}
      shell: bash

    - run: echo "$HOME/.local/share/beamup/installs/otp/${{ inputs.otp-version }}/bin" >> $GITHUB_PATH
      shell: bash

    - run: echo "$HOME/.local/share/beamup/installs/elixir/${{ inputs.elixir-version }}/bin" >> $GITHUB_PATH
      shell: bash
      if: ${{ inputs.elixir-version }} != ''
