name: Setup BEAM
inputs:
  otp-version:
    description: "The OTP version"
    required: true
  elixir-version:
    description: "The Elixir version (optional)"
  gleam-version:
    description: "The Gleam version (optional)"
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/../install.sh
      env:
        OTP_VERSION: ${{ inputs.otp-version }}
        ELIXIR_VERSION: ${{ inputs.elixir-version }}
        GLEAM_VERSION: ${{ inputs.gleam-version }}
      shell: bash

    - run: echo "$HOME/.local/share/beamup/bin" >> $GITHUB_PATH
      shell: bash
