name: Setup BEAM
inputs:
  otp-version:
    description: "The OTP version"
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/../install.sh ${{ inputs.otp-version }}
      shell: bash
    - run: echo "$HOME/.local/share/beamup/installs/otp/${{ inputs.otp-version }}" >> $GITHUB_PATH
      shell: bash
