name: Setup BEAM
inputs:
  otp-version:
    description: "The OTP version"
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/../scripts/setup_otp.sh ${{ inputs.otp-version }}
      shell: bash
