name: Build OTP release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The OTP version'
        required: true

jobs:
  ensure_release:
    runs-on: ubuntu-18.04
    name: "Ensure release (${{ github.event.inputs.version }})"
    steps:
      - run: gh api -XHEAD repos/erlang/otp/releases/tags/OTP-${{ github.event.inputs.version }}
        name: Check erlang/otp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: check-release
        name: Check wojtekmach/otp_releases 
        run: |
          if gh api -XHEAD repos/wojtekmach/otp_releases/releases/tags/OTP-${{ github.event.inputs.version }}; then 
            echo ::set-output name=exists::$(echo true)
          else
            echo ::set-output name=exists::$(echo false)
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          owner: wojtekmach
          repo: otp_releases
          commitish: main
          tag_name: OTP-${{ github.event.inputs.version }}
          prerelease: ${{ contains(github.event.inputs.version, 'rc') }}
        if: ${{ steps.check-release.outputs.exists == 'false' }}

  build:
    needs: [ensure_release]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15]
    steps:
    - uses: actions/checkout@v2

    - name: Set release name
      id: release-name
      run: echo ::set-output name=name::otp-${{ github.event.inputs.version }}-$(uname -sm | tr '[:upper:]' '[:lower:]' | tr ' ' '-')

    - id: asset-exists
      name: Check if release asset exists
      run: |
        release_id=$(gh api repos/wojtekmach/otp_releases/releases/tags/OTP-${{ github.event.inputs.version }} | jq .id)
        if gh api repos/wojtekmach/otp_releases/releases/${release_id}/assets | jq -r '.[].name' | grep ${{ steps.release-name.outputs.name }}; then
          echo ::set-output name=exists::$(echo true)
        else
          echo ::set-output name=exists::$(echo false)
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: TMPDIR=$PWD/tmp ./scripts/build_otp.sh ${{ github.event.inputs.version }}
      if: ${{ steps.asset-exists.outputs.exists == 'false' }}

    # - run: mkdir -p tmp/beamup && cd tmp/beamup && mkdir -p ${{ steps.release-name.outputs.name }} && tar czf ${{ steps.release-name.outputs.name }}.tar.gz ${{ steps.release-name.outputs.name }}
    #   if: ${{ steps.asset-exists.outputs.exists == 'false' }}

    - run: gh release upload -R wojtekmach/otp_releases OTP-${{ github.event.inputs.version }} tmp/beamup/${{ steps.release-name.outputs.name }}.tar.gz
      name: Upload asset
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      if: ${{ steps.asset-exists.outputs.exists == 'false' }}
