on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: CI
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, macos-10.15]
    steps:
      - uses: actions/checkout@v2
      - uses: ./setup-beam
        with:
          otp-version: 24.0-rc1
      - run: erl -eval 'halt().'
