on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: CI
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, macos-10.15]
    steps:
      - uses: actions/checkout@v2
      - uses: ./setup-beam
        with:
          otp-version: 24.0-rc1
      - run: erl -eval 'io:format("Erlang/OTP ~s ~s~n", [erlang:system_info(otp_release), erlang:system_info(system_architecture)]), init:stop().'
        name: Test OTP version
