on:
  push:

jobs:
  test:
    runs-on: ubuntu-16.04
    name: CI
    steps:
      - uses: actions/checkout@v2
      - uses: ./setup-beam
        with:
          otp-version: 24.0-rc1
      - run: erl -eval 'halt().'
