on:
  schedule:
    # every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'reason for sync'
        required: false

jobs:
  sync_otp_releases:
    name: Sync OTP releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/sync_otp_releases.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
